{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_face_detection",
    "module": "google_mlkit_face_detection_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_face_detection_profile-1.0.aar",
          "url": "google_mlkit_face_detection_profile-1.0.aar",
          "size": 7235,
          "sha512": "5309a506f29a114b94b2805e2fb719567749ff400c1d295f4901652f5ab0143fa854348f8aa13b5c4417b0420d7a71b3acf3be091fa89bf95ec3f551b39f5ffa",
          "sha256": "62dec64ec391dbee7cd454505e83c6a4e9144c248e9afec298e46f0ea9379399",
          "sha1": "2394a4929be19a6385eba3faebbe51f02c138331",
          "md5": "36996c6fbba2e84d1f3742aa220857e4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.7"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_face_detection_profile-1.0.aar",
          "url": "google_mlkit_face_detection_profile-1.0.aar",
          "size": 7235,
          "sha512": "5309a506f29a114b94b2805e2fb719567749ff400c1d295f4901652f5ab0143fa854348f8aa13b5c4417b0420d7a71b3acf3be091fa89bf95ec3f551b39f5ffa",
          "sha256": "62dec64ec391dbee7cd454505e83c6a4e9144c248e9afec298e46f0ea9379399",
          "sha1": "2394a4929be19a6385eba3faebbe51f02c138331",
          "md5": "36996c6fbba2e84d1f3742aa220857e4"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_face_detection_profile-1.0-sources.jar",
          "url": "google_mlkit_face_detection_profile-1.0-sources.jar",
          "size": 3334,
          "sha512": "c9eae824afa7f730aafe5f9acb770234459181bd6dd006cd10ace2b7b525f68fa7d6c7b098736be82e1f9f17b52816ccffa157546e9fc916a69f4a6f45361221",
          "sha256": "78d283266cda3ef0de46e08508ce8263e8ff9edfbecf63d70bd9fa2948b4b87f",
          "sha1": "55da4311d030e19b64c9dec1add182ea81b2fccd",
          "md5": "c247f4a86e19ea8e52e2826e7c61ffba"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_face_detection_profile-1.0-javadoc.jar",
          "url": "google_mlkit_face_detection_profile-1.0-javadoc.jar",
          "size": 261954,
          "sha512": "86ac35249882453863c6af5dd795fc528cd0a154939b8d1f4dd32812a16594b8d70af7f504e0bf1111228e49bb6f1af1a132007e4299321a95c14d4f9b0e691f",
          "sha256": "657872db81bbac891e8f46af9200e129b5cea2ffc271867bafa099bf2bc203fe",
          "sha1": "37cc1f255a7abcaaf300bafab25ed42028c6d123",
          "md5": "5c1f3af81fc430e173beda0f3190a931"
        }
      ]
    }
  ]
}
