{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_commons",
    "module": "google_mlkit_commons_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_profile-1.0.aar",
          "url": "google_mlkit_commons_profile-1.0.aar",
          "size": 10899,
          "sha512": "ba2cb17e2848accd4cbc3c1f519159cec16b46831757cc63e972e10de72c43dd0a07d999eb620ab447cff4a2513845fbdcc07d748e7168882c3c98a88f60ded2",
          "sha256": "c6f13ac835df85ede7f5c0f008dcb0589e81508a9951f23ad2315c0d73dc0754",
          "sha1": "1f7934547a01c72cfc02cd1fc4fb20e24fe26509",
          "md5": "ed3f00aa5736ab84880a5f603608d170"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "vision-common",
          "version": {
            "requires": "17.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_commons_profile-1.0.aar",
          "url": "google_mlkit_commons_profile-1.0.aar",
          "size": 10899,
          "sha512": "ba2cb17e2848accd4cbc3c1f519159cec16b46831757cc63e972e10de72c43dd0a07d999eb620ab447cff4a2513845fbdcc07d748e7168882c3c98a88f60ded2",
          "sha256": "c6f13ac835df85ede7f5c0f008dcb0589e81508a9951f23ad2315c0d73dc0754",
          "sha1": "1f7934547a01c72cfc02cd1fc4fb20e24fe26509",
          "md5": "ed3f00aa5736ab84880a5f603608d170"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_profile-1.0-sources.jar",
          "url": "google_mlkit_commons_profile-1.0-sources.jar",
          "size": 3893,
          "sha512": "a9c817d4383cd1bf53c4babfc97297192dd17417126329051874bcfdaa354a8c3f493306d4dab79ee4aaaa1f9b9d29266756b4aa5f7e75f7d3f229ed7da7c244",
          "sha256": "212b2ff21a24b11c4b34d87730b9a3070b0fc85e3db3836c98b063cecb74c9cc",
          "sha1": "390f524d1f225b42bd9497722fd72e4191efdf59",
          "md5": "d4654ea48eb76808d75ca50a55283c85"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_commons_profile-1.0-javadoc.jar",
          "url": "google_mlkit_commons_profile-1.0-javadoc.jar",
          "size": 276364,
          "sha512": "92b27671b717bc9a9498046320d0a6577ddb14546433c38671b922a34575e22cc2823318d1d434012da682d1d68e3b54aa8ea138e9b8b2804915475e1afbae9a",
          "sha256": "f0076722779a1f9504e5fe2fe5c95e7bd5538d571e2c0103a736ea42df88c832",
          "sha1": "92e24bdf6f32d81199c04d65283bcccdfa8a605c",
          "md5": "5c0a803f5600fff3df48b70db7fe0e82"
        }
      ]
    }
  ]
}
