{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_sdk_core",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_sdk_core_plugin",
          "module": "flutter_sdk_core_plugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_face_detection",
          "module": "google_mlkit_face_detection_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.flutter.stripe",
          "module": "stripe_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 18511299,
          "sha512": "86a38a0aa6fb384b93ed9245b9a7a596c1de1b1cc191adc199d9f4f9b55e0c5501505484634f6294c9dd81a7a8bf5b03d842e1602efeff3ccc4b0f2bd8bc411b",
          "sha256": "0611a67b44f2c8e592e9b89fab2ab701290b2f2695a750c7b34bcdd708464b2e",
          "sha1": "ed12f74a9eaa3394dc2b9f57686f5b23dd8ee45f",
          "md5": "81c4c9f9cd2b580180dd4ed1b11024fe"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_sdk_core_plugin",
          "module": "flutter_sdk_core_plugin_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_face_detection",
          "module": "google_mlkit_face_detection_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.flutter.stripe",
          "module": "stripe_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 18511299,
          "sha512": "86a38a0aa6fb384b93ed9245b9a7a596c1de1b1cc191adc199d9f4f9b55e0c5501505484634f6294c9dd81a7a8bf5b03d842e1602efeff3ccc4b0f2bd8bc411b",
          "sha256": "0611a67b44f2c8e592e9b89fab2ab701290b2f2695a750c7b34bcdd708464b2e",
          "sha1": "ed12f74a9eaa3394dc2b9f57686f5b23dd8ee45f",
          "md5": "81c4c9f9cd2b580180dd4ed1b11024fe"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1272,
          "sha512": "e33a46e2057170d5b537dac1c9a453f8a8249ef998a6395f85cb0cc12f7df580323d1f0e58f4aab4bf35f66719aac5f870d918224f6c98f6261012e77794900a",
          "sha256": "cd8482071cce48a0f110cb08752f07f713415835a1f250d2d3d10d4ef24a50e9",
          "sha1": "8f110c6493ff355d2f8a2c53d326d44ecd150862",
          "md5": "fd1907ee0bd2c8c77f9b10b86117378d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
