{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_sdk_core_plugin",
    "module": "flutter_sdk_core_plugin_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sdk_core_plugin_debug-1.0.aar",
          "url": "flutter_sdk_core_plugin_debug-1.0.aar",
          "size": 2739,
          "sha512": "b746fa7f8af12efa4b34529bb954d7e0252faedb76f4076e94f04bc5bc66b9e21e626a0471bd27b18aeac6566ea00bcff5499d63385055368bf8ff2eab3b947e",
          "sha256": "9c9614d41da8ab04ba30a5d5192d6a018b90039c4561972f23a29ff7a2d993d6",
          "sha1": "13e4ac08763278dba04dfd4a96f4a165b84a0786",
          "md5": "ef3fcd8be4defa1c5a47fb5c8e3e1a60"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sdk_core_plugin_debug-1.0.aar",
          "url": "flutter_sdk_core_plugin_debug-1.0.aar",
          "size": 2739,
          "sha512": "b746fa7f8af12efa4b34529bb954d7e0252faedb76f4076e94f04bc5bc66b9e21e626a0471bd27b18aeac6566ea00bcff5499d63385055368bf8ff2eab3b947e",
          "sha256": "9c9614d41da8ab04ba30a5d5192d6a018b90039c4561972f23a29ff7a2d993d6",
          "sha1": "13e4ac08763278dba04dfd4a96f4a165b84a0786",
          "md5": "ef3fcd8be4defa1c5a47fb5c8e3e1a60"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_sdk_core_plugin_debug-1.0-sources.jar",
          "url": "flutter_sdk_core_plugin_debug-1.0-sources.jar",
          "size": 1317,
          "sha512": "0ab816ab8282050d62555a386d0aae8fa3a589e2f335665b297d77eed00cf64e4bc89d2bd3d56658ca72e0f065ab27a07164c4af6acc2f7573406db6deba375a",
          "sha256": "452186a0b30e9d0d9bda9e7734b7710e7e809634340dc4f15e9b2b9c29955709",
          "sha1": "afc6cbc6a9a17567742dcb84d8ab50f0435739e6",
          "md5": "84e1205cd75bab15735915e6af9c4f9e"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_sdk_core_plugin_debug-1.0-javadoc.jar",
          "url": "flutter_sdk_core_plugin_debug-1.0-javadoc.jar",
          "size": 262381,
          "sha512": "b076e50a5e8229cd54f84d5312754404be4ec0e93b309f205eb5174cbb3ee354bfb8a4d282922b580400c2c20b7417d195516f99d117614c160c154881594914",
          "sha256": "0540218f381bd0870bb4405b3b963a0cc230c8aaeda881ca51a18d7c86773883",
          "sha1": "d35925126b12146920bbed4e8c7f807afc358584",
          "md5": "bee71e21182df20d4ff4295026a9705c"
        }
      ]
    }
  ]
}
