{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google_mlkit_face_detection",
    "module": "google_mlkit_face_detection_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_face_detection_release-1.0.aar",
          "url": "google_mlkit_face_detection_release-1.0.aar",
          "size": 6870,
          "sha512": "5a2b0c7da5d17e9b04e1a81e49776438af51d7745682b7c0fcf694ade386d9690618046d7ade1d28b3ede36069597ff99a6647590848398f9349fea627b8e58f",
          "sha256": "de5ccf22e66f178dca92a457e83377985a327030745fa05e637e0a72ad72d0e8",
          "sha1": "4a96050e8d634d7811a74c8837dac23a7a1aeae8",
          "md5": "77d6a7428e4b2a0f2f7f4a20a82da134"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.1.7"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "google_mlkit_face_detection_release-1.0.aar",
          "url": "google_mlkit_face_detection_release-1.0.aar",
          "size": 6870,
          "sha512": "5a2b0c7da5d17e9b04e1a81e49776438af51d7745682b7c0fcf694ade386d9690618046d7ade1d28b3ede36069597ff99a6647590848398f9349fea627b8e58f",
          "sha256": "de5ccf22e66f178dca92a457e83377985a327030745fa05e637e0a72ad72d0e8",
          "sha1": "4a96050e8d634d7811a74c8837dac23a7a1aeae8",
          "md5": "77d6a7428e4b2a0f2f7f4a20a82da134"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_face_detection_release-1.0-sources.jar",
          "url": "google_mlkit_face_detection_release-1.0-sources.jar",
          "size": 3334,
          "sha512": "c9eae824afa7f730aafe5f9acb770234459181bd6dd006cd10ace2b7b525f68fa7d6c7b098736be82e1f9f17b52816ccffa157546e9fc916a69f4a6f45361221",
          "sha256": "78d283266cda3ef0de46e08508ce8263e8ff9edfbecf63d70bd9fa2948b4b87f",
          "sha1": "55da4311d030e19b64c9dec1add182ea81b2fccd",
          "md5": "c247f4a86e19ea8e52e2826e7c61ffba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "google_mlkit_face_detection_release-1.0-javadoc.jar",
          "url": "google_mlkit_face_detection_release-1.0-javadoc.jar",
          "size": 261954,
          "sha512": "86ac35249882453863c6af5dd795fc528cd0a154939b8d1f4dd32812a16594b8d70af7f504e0bf1111228e49bb6f1af1a132007e4299321a95c14d4f9b0e691f",
          "sha256": "657872db81bbac891e8f46af9200e129b5cea2ffc271867bafa099bf2bc203fe",
          "sha1": "37cc1f255a7abcaaf300bafab25ed42028c6d123",
          "md5": "5c1f3af81fc430e173beda0f3190a931"
        }
      ]
    }
  ]
}
