{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_sdk_core",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_sdk_core_plugin",
          "module": "flutter_sdk_core_plugin_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_face_detection",
          "module": "google_mlkit_face_detection_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.flutter.stripe",
          "module": "stripe_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 8791076,
          "sha512": "106d45f503f23d532c931ad4b7d5a4af9e301d1963033f89a1d62b7539c007bc1fa8c34ea38115e7a51a4f66d761c8ae7154bfae0a85748420057b451a058f92",
          "sha256": "7aa835da5c33b6d7670d637a3d59b9aadcceef934c41ea6d5d4e39316fd674e1",
          "sha1": "a8c17b691fe4618cf8127499ba8f147bd4492cb1",
          "md5": "3dc14141c07073921e1e7f5d3a843a7f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutter_sdk_core_plugin",
          "module": "flutter_sdk_core_plugin_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_commons",
          "module": "google_mlkit_commons_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google_mlkit_face_detection",
          "module": "google_mlkit_face_detection_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.flutter.stripe",
          "module": "stripe_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 8791076,
          "sha512": "106d45f503f23d532c931ad4b7d5a4af9e301d1963033f89a1d62b7539c007bc1fa8c34ea38115e7a51a4f66d761c8ae7154bfae0a85748420057b451a058f92",
          "sha256": "7aa835da5c33b6d7670d637a3d59b9aadcceef934c41ea6d5d4e39316fd674e1",
          "sha1": "a8c17b691fe4618cf8127499ba8f147bd4492cb1",
          "md5": "3dc14141c07073921e1e7f5d3a843a7f"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1272,
          "sha512": "e33a46e2057170d5b537dac1c9a453f8a8249ef998a6395f85cb0cc12f7df580323d1f0e58f4aab4bf35f66719aac5f870d918224f6c98f6261012e77794900a",
          "sha256": "cd8482071cce48a0f110cb08752f07f713415835a1f250d2d3d10d4ef24a50e9",
          "sha1": "8f110c6493ff355d2f8a2c53d326d44ecd150862",
          "md5": "fd1907ee0bd2c8c77f9b10b86117378d"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
