{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.flutter_sdk_core",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 8786619,
          "sha512": "4012511d33084bf7f78955d1c3b88bedb3a1f56496dc4270073d4eaab6c48ce060399802819e71160d444838ff4e03fafd1b48e324e62e0b2de864c86fd07d5b",
          "sha256": "34a8d63d020db74beb7de8dba51ecc6221483579ba7335285f95ed561b9806a2",
          "sha1": "84dcd0b31d80aa2deb237d8efb537e181c023419",
          "md5": "498dbd3dd31dcbcf0cd09d70a528dbcd"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 8786619,
          "sha512": "4012511d33084bf7f78955d1c3b88bedb3a1f56496dc4270073d4eaab6c48ce060399802819e71160d444838ff4e03fafd1b48e324e62e0b2de864c86fd07d5b",
          "sha256": "34a8d63d020db74beb7de8dba51ecc6221483579ba7335285f95ed561b9806a2",
          "sha1": "84dcd0b31d80aa2deb237d8efb537e181c023419",
          "md5": "498dbd3dd31dcbcf0cd09d70a528dbcd"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1145,
          "sha512": "c9b373a53a9645802ead663dac3e9c9eddf100a42e147cf46399a47a8b4dfeb439ab63065650880b522f784311a08ffdc343e3d996c875675eae03279b56a404",
          "sha256": "1b61bb79514ba50d35aea644c52b9024497de4d971305e9c62f93e9abce4bfdb",
          "sha1": "9e3343a35a0940480dc5d4b91cbde4959c4e1b65",
          "md5": "9855fc73d09377c45336aec2ce01863f"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
