{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
    "module": "flutter_plugin_android_lifecycle_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 2526,
          "sha512": "04fab3d71042813fc354e0c93cd7d82ae37fff7ae9b5b676c9006d4c290514206be04f1c83cd1c1c8a60106c1308c29b93a9218f5a65446a838229267ecaa193",
          "sha256": "57e6f44471908fd2b1a156e7ba374219dd9d757ac120814e4ab642c17a4c2e96",
          "sha1": "515176c06213bd0c5dd33ed0d517449a47f83512",
          "md5": "5f39dcc2ceb0bfb83b0af49fe93cf23b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-3452d735bd38224ef2db85ca763d862d6326b17f"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0.aar",
          "size": 2526,
          "sha512": "04fab3d71042813fc354e0c93cd7d82ae37fff7ae9b5b676c9006d4c290514206be04f1c83cd1c1c8a60106c1308c29b93a9218f5a65446a838229267ecaa193",
          "sha256": "57e6f44471908fd2b1a156e7ba374219dd9d757ac120814e4ab642c17a4c2e96",
          "sha1": "515176c06213bd0c5dd33ed0d517449a47f83512",
          "md5": "5f39dcc2ceb0bfb83b0af49fe93cf23b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0-sources.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0-sources.jar",
          "size": 2659,
          "sha512": "d848b9ac3a80bd88694f7d35de2abc2866f65393d53caa1f49513063e17fe497a4b7e1ed09dc3736f529a166f1491dfb78c703a51f0fe0950082488869f2b352",
          "sha256": "2930f0a83f74dc7a57026b471c4443a3e5cb4f8b5f80bf45d161dd31675194c7",
          "sha1": "82b1c36d1af62197547e6c132ae64f520e3ad7a7",
          "md5": "fb7b3ee0458fe0f3ec0a8116c68f72ed"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_plugin_android_lifecycle_debug-1.0-javadoc.jar",
          "url": "flutter_plugin_android_lifecycle_debug-1.0-javadoc.jar",
          "size": 269824,
          "sha512": "605d70f3aadf20a81faf2d66b92228404a35593deaea4db210bc60fc23bedef640a748b2b75946de1a161788f66780ec5eb134a651272b6f0c8b7677d9f5b0d9",
          "sha256": "91c513402a3eae0a149c75b64ff8e580c8e90e560a99e7f5583f4f2489c76f6d",
          "sha1": "cc432994050df65ba1efe849e243797e8953cc71",
          "md5": "37fd5147acc1eb36961d7172612f2c44"
        }
      ]
    }
  ]
}
